const BlogData = [
    {
        id: 1,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-1.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 2,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-2.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 3,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-3.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 4,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-4.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 5,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-5.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 6,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-2.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 7,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-4.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 8,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-3.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },
    {
        id: 9,
        date: "January 01, 2022",
        category: "Business",
        title: "The most advance business plan",
        cover: "/images/singlepage/blog-1.jpg",
        para: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores laboriosam aut tempore facere laudantium reiciendis excepturi distinctio explicabo perspiciatis enim sequi provident aliquid id porro impedit est, quos quod vel?',
    },

];

export default BlogData;